services:
    php:
        build: ./docker/php
        container_name: symfony-php
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - db

    nginx:
        image: nginx:1.25
        container_name: symfony-nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    db:
        image: mysql:8.0
        container_name: symfony-db
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: main
            MYSQL_USER: symfony
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    adminer:
        image: adminer
        container_name: symfony-adminer
        ports:
            - "8081:8080"

volumes:
    db_data:
